### ISSUE TITLE
Investigate accuracy in white rooms

### ISSUE THREAD

**Issue by DerHlopec** [Kasiama/PhotoApp#3]

**Comment by Kasiama** [comment]
I made deep investigation for your ticket through my application that can show feature points in the scene. We can conclude that Arkit really can't accurately appreciate  objects that  are located on a white background, especially when we have a white floor. 
![IMG_0564](https://user-images.githubusercontent.com/38030528/73176132-be8ca700-411c-11ea-9d6c-ca8f115eec95.PNG)
![IMG_0560](https://user-images.githubusercontent.com/38030528/73176134-c0566a80-411c-11ea-9c46-0df09c1d7cdb.PNG)
![IMG_0558](https://user-images.githubusercontent.com/38030528/73176136-c1879780-411c-11ea-8f21-ea018888942d.PNG)
![IMG_0559](https://user-images.githubusercontent.com/38030528/73176138-c2202e00-411c-11ea-88fd-9f954864e8da.PNG)
